fastlane_version "1.92.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Testing"
  lane :test_fast do
    slack(
      message: "This is a test"
    )
  end

  desc "Setup provisioning/certs"
  lane :provision do
    cert(development: true, output_path: "provisioning")
    cert(output_path: "provisioning")

    sigh(development: true, output_path: "provisioning")
    sigh(adhoc: true, output_path: "provisioning")

    #force recreation of profile
    #sigh(adhoc: true, output_path: "provisioning", force: true)
    #
    sigh(output_path: "provisioning")
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Take pics"
  lane :pictures do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
